name: Deploy webhook to cloud run

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: configure docker
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Build docker image
        run: |
          IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .

      - name: push docker image
        run: |
          IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}"
          docker push "$IMAGE"
      - name: deploy to cloud run
        run: |
          IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/${{ vars.SERVICE_NAME }}:${{ github.sha }}"
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image "$IMAGE" \
            --region ${{ vars.REGION }} \
            --service-account sa-webhook-runtime@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com \
            --platform managed \
            --allow-unauthenticated

        
