name: Deploy webhook to cloud run

on:
  push:
    branches: ["main"]

jobs:
  auth:
    name: Authenticate & Setup GCP
    runs-on: ubuntu-22.04
    environment: dev

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          audience: ${{ secrets.AUDIENCE }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev
  build:
    name: Build Docker Image
    runs-on: ubuntu-22.04
    needs: auth

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }} .

  push:
    name: Push Docker Image
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          audience: ${{ secrets.AUDIENCE }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Configure Docker auth
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Push Docker image
        run: |
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }}

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-22.04
    needs: push
    environment: dev

    steps:
      - name: Google Auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          audience: ${{ secrets.AUDIENCE }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.SERVICE_NAME }} \
            --image ${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }} \
            --region ${{ vars.REGION }} \
            --service-account ${{ secrets.RUNTIME_SERVICE_ACCOUNT }} \
            --platform managed \
            --allow-unauthenticated      

  
# jobs:
#   deploy:
#     runs-on: ubuntu-22.04
#     environment: dev

#     permissions:
#       contents: read
#       id-token: write

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Google Auth
#         uses: google-github-actions/auth@v3
#         with:
#           workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
#           service_account: ${{ secrets.SERVICE_ACCOUNT }}
#           audience: ${{ secrets.AUDIENCE }}

#       - name: Configure gcloud
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.PROJECT_ID }}

#       - name: configure docker
#         run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

#       - name: Build docker image
#         run: |
#           IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }}"
#           docker build -t "$IMAGE" .

#       - name: push docker image
#         run: |
#           IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }}"
#           docker push "$IMAGE"
#       - name: deploy to cloud run
#         run: |
#           IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ vars.REPO }}/webhook-cicd:${{ github.sha }}"
#           gcloud run deploy ${{ vars.SERVICE_NAME }} \
#             --image "$IMAGE" \
#             --set-env-vars "TWILIO_ACCOUNT_SID=ACf6569de962753c04d1498f2c3e04ac8d,TWILIO_AUTH_TOKEN=1adccb2bf505c155c31193652475a6b0,TWILIO_VERIFY_SERVICE_SID=VA3598aa87911d774d111ff09deefd5f84" \
#             --region ${{ vars.REGION }} \
#             --service-account ${{ secrets.RUNTIME_SERVICE_ACCOUNT }} \
#             --platform managed \
#             --allow-unauthenticated

        
